### stacking demo
# Attention: you need to change these frames in the load_static_tf.launch file if the table setup changes
object_frame_id: object_base # NOT USED
object_0_frame_id: object_0_base
object_1_frame_id: object_1_base
object_2_frame_id: object_2_base

middle_frame_id: middle # NOT USED
tower_frame_id: tower_base

base_frame_id: panda_link0


object_height: 0.04 
tower_height: 0.12 # need to set from config! 
drop_offset_z : 0.04 # positive is above the object!


arm_velocity_scaling_drop: 0.3
arm_velocity_scaling_grasp: 0.1
