# Define the goal
string name
---
# Define the result
bool success
float64 probability
# int32[] targetBB
grasp_demo/BoundingBox targetBB
---
# Define the feedback
bool in_progress
grasp_demo/BoundingBoxes detectedBB
