cartesian_velocity_controller:
    type: panda_control/CartesianVelocityController
    arm_id: panda
    rate_limiting:
        linear:
            velocity: 0.5
            acceleration: 8.0
            jerk: 1000.0
        angular:
            velocity: 0.5
            acceleration: 5.0
            jerk: 2000.0
    max_duration_between_commands: 0.1  # velocity is set to 0 if no new command is received within this time

joint_space_controller:
  simulation: false
  type: moma_controllers/JointSpaceController
  joint_names:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  lower_limit: [-6.28, -2.41, -6.28, -2.66, -6.28, -2.23, -6.28]
  upper_limit: [6.28, 2.41, 6.28, 2.66, 6.28, 2.23, 6.28]
  max_velocity: 0.3
  max_acceleration: 0.1
  gain: 1.0
  tolerance: 0.017 # 1 deg
  pid_gains:
    panda_joint1: { p: 100.0, i: 0.0, d: 10.0, i_clamp_min: -100.0, i_clamp_max: 100.0 }
    panda_joint2: { p: 100.0, i: 0.0, d: 10.0, i_clamp_min: -5.0, i_clamp_max: 5.0 }
    panda_joint3: { p: 100.0, i: 0.0, d: 10.0, i_clamp_min: -1.0, i_clamp_max: 1.0 }
    panda_joint4: { p: 100.0, i: 0.0, d: 10.0, i_clamp_min: -1.0, i_clamp_max: 1.0 }
    panda_joint5: { p: 200.0, i: 0.0, d: 0.2, i_clamp_min: -1.0, i_clamp_max: 1.0 }
    panda_joint6: { p: 200.0, i: 0.0, d: 10.0, i_clamp_min: -1.0, i_clamp_max: 1.0 }
    panda_joint7: { p: 100.0, i: 0.0, d: 10.0, i_clamp_min: -0.1, i_clamp_max: 0.1 }

mpc_controller:
  type: moma_controllers/PandaMpcController
  simulation: false
  arm_id: panda

  robot_name: "panda"
  base_link: base_link
  tool_link: panda_hand
  joint_names:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  mpc_frequency: 20
  command_topic: "/joints_position_controller/command"
  path_topic: "/desired_path"

  gains:
    panda_joint1: { p: 100.0, i: 0.0, d: 20.0, i_clamp_min: -100.0, i_clamp_max: 100.0 }
    panda_joint2: { p: 100.0, i: 0.0, d: 20.0, i_clamp_min: -5.0, i_clamp_max: 5.0 }
    panda_joint3: { p: 100.0, i: 0.0, d: 20.0, i_clamp_min: -1.0, i_clamp_max: 1.0 }
    panda_joint4: { p: 100.0, i: 0.0, d: 20.0, i_clamp_min: -1.0, i_clamp_max: 1.0 }
    panda_joint5: { p: 100.0, i: 0.0, d: 20.0, i_clamp_min: -1.0, i_clamp_max: 1.0 }
    panda_joint6: { p: 100.0, i: 0.0, d: 20.0, i_clamp_min: -1.0, i_clamp_max: 1.0 }
    panda_joint7: { p: 100.0, i: 0.0, d: 20.0, i_clamp_min: -0.1, i_clamp_max: 0.1 }