cartesian_velocity_controller:
    type: panda_control/CartesianVelocityController
    arm_id: panda
    rate_limiting:
        linear:
            velocity: 0.5
            acceleration: 8.0
            jerk: 1000.0
        angular:
            velocity: 0.5
            acceleration: 5.0
            jerk: 2000.0
    max_duration_between_commands: 0.1  # velocity is set to 0 if no new command is received within this time

joint_space_controller:
  simulation: false
  type: moma_controllers/JointSpaceController
  joint_names:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  lower_limit: [-2.8973, -1.7628, -2.8973, -3.0718, -2.8973, -0.0175, -2.8973]
  upper_limit: [2.8973, 1.7628, 2.8973, 0.0698, 2.8973, 3.7525, 2.8973]
  max_velocity: 0.3
  max_acceleration: 0.1
  gain: 1.0
  tolerance: 0.017 # 1 deg
  pid_gains:
    panda_joint1: { p: 100.0, i: 0.0, d: 10.0, i_clamp_min: -100.0, i_clamp_max: 100.0 }
    panda_joint2: { p: 100.0, i: 0.0, d: 10.0, i_clamp_min: -5.0, i_clamp_max: 5.0 }
    panda_joint3: { p: 100.0, i: 0.0, d: 10.0, i_clamp_min: -1.0, i_clamp_max: 1.0 }
    panda_joint4: { p: 100.0, i: 0.0, d: 10.0, i_clamp_min: -1.0, i_clamp_max: 1.0 }
    panda_joint5: { p: 200.0, i: 0.0, d: 0.2, i_clamp_min: -1.0, i_clamp_max: 1.0 }
    panda_joint6: { p: 200.0, i: 0.0, d: 10.0, i_clamp_min: -1.0, i_clamp_max: 1.0 }
    panda_joint7: { p: 100.0, i: 0.0, d: 10.0, i_clamp_min: -0.1, i_clamp_max: 0.1 }

mpc_controller:
  type: moma_controllers/PandaMpcController
  simulation: false
  arm_id: panda

  robot_name: "panda"
  base_link: base_link
  tool_link: tool_frame
  joint_names:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  mpc_frequency: 20
  command_topic: "/joints_position_controller/command"
  path_topic: /mpc_reference_path

  gains:
    panda_joint1: { p: 100.0, i: 0.0, d: 20.0, i_clamp_min: -100.0, i_clamp_max: 100.0 }
    panda_joint2: { p: 100.0, i: 0.0, d: 20.0, i_clamp_min: -5.0, i_clamp_max: 5.0 }
    panda_joint3: { p: 100.0, i: 0.0, d: 20.0, i_clamp_min: -1.0, i_clamp_max: 1.0 }
    panda_joint4: { p: 100.0, i: 0.0, d: 20.0, i_clamp_min: -1.0, i_clamp_max: 1.0 }
    panda_joint5: { p: 100.0, i: 0.0, d: 20.0, i_clamp_min: -1.0, i_clamp_max: 1.0 }
    panda_joint6: { p: 100.0, i: 0.0, d: 20.0, i_clamp_min: -1.0, i_clamp_max: 1.0 }
    panda_joint7: { p: 100.0, i: 0.0, d: 20.0, i_clamp_min: -0.1, i_clamp_max: 0.1 }

path_admittance_controller:
  type: moma_controllers/PathAdmittanceController

  verbose: true
  wrench_topic: /ft_compensated
  path_in_topic: /desired_path
  path_out_topic: /mpc_reference_path
  
  kp_linear_gains: [0.01, 0.01, 0.01]
  kp_angular_gains: [0.01, 0.01, 0.01]
  ki_linear_gains: [ 0.0, 0.0, 0.0 ]
  ki_angular_gains: [ 0.0, 0.0, 0.0 ]
  force_integral_max: [1.0, 1.0, 1.0]
  torque_integral_max: [1.0, 1.0, 1.0]

  force_threshold: [2.0, 2.0, 2.0]
  torque_threshold: [0.5, 0.5, 0.5]