door_opening_joint_velocity_controller:
    type: door_opening_on_real_robot_demo/DoorOpeningJointVelocityController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    max_duration_between_commands: 0.1
    max_velocity: [2.1750, 2.1750, 2.1750, 2.1750, 2.6100, 2.6100, 2.6100]
    max_acceleration: [15, 7.5, 10, 12.5, 15, 20, 20]
    max_jerk: [7500, 3750, 5000, 6250, 7500, 10000, 10000]


