controller_list:
  - name: fake_hand_controller
    joints:
      - panda_finger_joint1
  - name: fake_arm_controller
    joints:
      - base_link_joint_x
      - base_link_joint_y
      - base_link_joint_th
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7