# Config file for the combined mission
# Namespaces mirror (optionally) the state for better readability

SETUP:
  default_outcome: Completed
  waypoints_file_path: $(find moma_mission)/config/state_machine/piloting_waypoints.yaml

IDLE:
  default_outcome: ExecuteManipulationPlan

OPEN_GRIPPER:
  default_outcome: None
  gripper_action_name: /panda/franka_gripper/gripper_action
  position: 0.03
  max_effort: 20
  tolerance: 0.001
  timeout: 5.0

CLOSE_GRIPPER:
  default_outcome: None
  gripper_action_name: /panda/franka_gripper/gripper_action
  position: 0.0
  max_effort: 20
  tolerance: 0.001
  timeout: 5.0

HOME_ROBOT:
  default_outcome: None
  action_name: /joint_space_controller_server
  manager_namespace: panda
  startlist: ['joint_space_controller']
  stoplist: ['mpc_controller', 'path_passthrough_controller', 'effort_joint_trajectory_controller']
  joints_configurations:
    - [0, -0.885, 0, -2.1, 0, 1.571, 0]

# hack to avoid self collision in the end
HOME_ROBOT_FINAL:
  default_outcome: None
  action_name: /joint_space_controller_server
  manager_namespace: panda
  startlist: ['joint_space_controller']
  stoplist: ['mpc_controller', 'path_passthrough_controller', 'effort_joint_trajectory_controller']
  joints_configurations:
    - [-0.65, -0.885, 0, -2.1, 0, 1.571, 0]

REACH_DETECTION_HOTSPOT:
  default_outcome: Completed
  goal_action_topic: /move_base
  target_frame: navigation_target
  goal_pose_topic: /move_base_simple/goal
  base_pose_topic: /base_pose_measured
  base_odometry_topic: /base_odom

  manager_namespace: smb
  startlist: ['smb_diff_drive']
  stoplist: []

  timeout: 10000.0
  tolerance_m: 0.30
  tolerance_deg: 50

WAYPOINT_FOLLOWING:
  default_outcome: None
  goal_action_topic: /move_base
  goal_pose_topic: /move_base_simple/goal
  base_pose_topic: /base_pose_measured
  base_odometry_topic: /camera/odom/sample

  manager_namespace: smb
  startlist: ['smb_diff_drive']
  stoplist: []

  timeout: 10000.0
  tolerance_m: 0.30
  tolerance_deg: 50

DETECTION_DECISION:
  default_outcome: Failure

OBSERVATION_POSE:
  default_outcome: None
  sample_name: observation
  map_frame: world
  object_frame: valve_gt
  camera_frame: hand_eye_color_optical_frame
  controlled_frame: tool_frame
  object_size: 0.20
  camera_info_topic: "/camera_info"
  lateral_view_angle_deg: 20
  image_fill_ratio: 0.5
  heading: [1, 0, 0]

OBSERVATION_APPROACH:
  default_outcome: None
  duration: 5.0
  control_frame: tracking_camera_odom
  target_frame: observation
  startlist: ['mpc_controller', 'path_passthrough_controller'] #, 'path_admittance_controller' ]
  stoplist: ['joint_space_controller']
  manager_namespace: panda

MODEL_FIT_VALVE:
  default_outcome: None
  dummy: false
  dummy_position: [0.8, 0.0, 0.5]
  dummy_orientation: [0.0, 0.707, 0.0, 0.707]

MODEL_URDF_VALVE:
  default_outcome: None

  poses_topic: /valve_poses
  turning_angle_deg: 120.0

APPROACH_VALVE:
  default_outcome: None
  manager_namespace: panda
  startlist: ['mpc_controller', 'path_passthrough_controller']
  stoplist: ['joint_space_controller']

  poses_topic: /valve_poses
  offset: [0, 0, -0.1]
  section: 'first'

GRASP_VALVE:
  default_outcome: None
  manager_namespace: panda
  startlist: ['mpc_controller', 'path_passthrough_controller']
  stoplist: ['joint_space_controller']

  poses_topic: /valve_poses
  section: 'first'

MANIPULATE_VALVE:
  default_outcome: None
  manager_namespace: panda
  startlist: ['mpc_controller', 'path_passthrough_controller']
  stoplist: ['joint_space_controller']

  poses_topic: /valve_poses
  angular_speed: 0.5

BACKOFF_VALVE:
  default_outcome: None
  manager_namespace: panda
  startlist: [ 'mpc_controller', 'path_passthrough_controller' ]
  stoplist: [ 'joint_space_controller' ]

  poses_topic: /valve_poses
  offset: [ 0, 0, -0.1 ]
  section: 'last'
