OPEN_GRIPPER:
  default_outcome: None
  gripper_action_name: /panda/franka_gripper/gripper_action
  position: 0.03
  max_effort: 20
  tolerance: 0.001
  timeout: 5.0

CLOSE_GRIPPER:
  default_outcome: None
  gripper_action_name: /panda/franka_gripper/gripper_action
  position: 0.0
  max_effort: 20
  tolerance: 0.03
  timeout: 5.0

APPROACH_VALVE:
  default_outcome: None
  manager_namespace: panda
  startlist: ['mpc_controller', 'path_passthrough_controller']
  stoplist: ['effort_joint_trajectory_controller']

  turning_angle_deg: 0.0

MANIPULATE_VALVE:
  default_outcome: None
  manager_namespace: panda
  startlist: ['mpc_controller', 'path_passthrough_controller']
  stoplist: ['effort_joint_trajectory_controller']

  turning_angle_deg: 120.0
  turning_speed_deg: 20.0
