# Config file for the combined mission
# Namespaces mirror (optionally) the state for better readability

OPEN_GRIPPER:
  command_topic: /gripper_command
  position: 0.0   # must be between 0 and 1
  velocity: 0  # between 0 and 1
  effort: 0 # must be between 0 and 10

CLOSE_GRIPPER:
  command_topic: /gripper_command
  position: 0.55  # must be between 0 and 1
  velocity: 0.01  # between 0 and 1
  effort: 0.5   # must be between 0 and 10

HOME_ROBOT:
  action_name: /joint_space_controller_server
  controller_name: joint_space_controller
  manager_namespace: ''
  whitelist: [robotiq_2f_85_controller, joint_state_controller]
  joints_configurations:
    - [0, -0.785, 0, -2.1, 0, 1.571, 0.785]

FETCH_DETECTION:
  default_outcome: Completed
  detection_topic: "/object_keypoints_ros/pose"

REACH_DETECTION_HOTSPOT:
  default_outcome: Completed
  target_frame: navigation_target
  goal_pose_topic: /move_base_simple/goal
  base_pose_topic: /base_pose_measured
  base_odometry_topic: /base_odom
  roco_controller: MpcTrackLocalPlan
  controller_manager_namespace: /smb_highlevel_controller
  timeout: 10000.0
  tolerance_m: 0.30
  tolerance_deg: 50

REACH_VIEWPOINT:
  action_name: /joint_space_controller_server
  controller_name: joint_space_controller
  manager_namespace: ''
  whitelist: [robotiq_2f_85_controller, joint_state_controller]
  joints_configurations:
    - [1.57, -0.785, 0, -2.1, 0, 1.571, 0.785]
    - [-1.57, -0.785, 0, -2.1, 0, 1.571, 0.785]

LATERAL_GRASP:
  default_outcome: Completed
  controller_name: mpc_admittance_torque
  manager_namespace: /my_gen3
  whitelist: [reflex_controller]
  pose_topic_name: /target_pose
  path_topic_name: /desired_path

RESET_LATERAL_GRASP:
  default_outcome: FullRotationDone
  controller_name: mpc_admittance_torque
  manager_namespace: /my_gen3
  whitelist: [ robotiq_2f_85_controller, joint_state_controller ]
  pose_topic_name: /target_pose
  path_topic_name: /desired_path

MANIPULATE_VALVE:
  default_outcome: Completed
  controller_name: mpc_admittance_torque
  manager_namespace: /my_gen3
  whitelist: [robotiq_2f_85_controller, joint_state_controller]

  angle_step_deg: -120.0   # how much to rotate at once
  angle_end_deg: -120.0    # total desired rotation
  angle_delta_deg: 5.0    # controls trajectory discretization
  speed_deg: 5.0
  path_topic_name: /desired_path
