OPEN_GRIPPER:
  default_outcome: None
  gripper_action_name: /panda/franka_gripper/gripper_action
  position: 0.03
  max_effort: 20
  tolerance: 0.001
  timeout: 5.0

CLOSE_GRIPPER:
  default_outcome: None
  gripper_action_name: /panda/franka_gripper/gripper_action
  position: 0.0
  max_effort: 20
  tolerance: 0.03
  timeout: 5.0

RELEASE_GRIPPER:
  default_outcome: None
  gripper_action_name: /panda/franka_gripper/gripper_action
  position: 0.03
  max_effort: 20
  tolerance: 0.001
  timeout: 5.0

MODEL_VALVE:
  default_outcome: None

  poses_topic: /valve_poses
  turning_angle_deg: 120.0

APPROACH_VALVE:
  default_outcome: None
  manager_namespace: panda
  startlist: [ 'mpc_controller', 'path_passthrough_controller' ]
  stoplist: [ 'effort_joint_trajectory_controller' ]

  poses_topic: /valve_poses
  offset: [0, 0, -0.1]
  section: 'first'

GRASP_VALVE:
  default_outcome: None
  manager_namespace: panda
  startlist: [ 'mpc_controller', 'path_passthrough_controller' ]
  stoplist: [ 'effort_joint_trajectory_controller' ]

  poses_topic: /valve_poses
  section: 'first'

MANIPULATE_VALVE:
  default_outcome: None
  manager_namespace: panda
  startlist: [ 'mpc_controller', 'path_passthrough_controller' ]
  stoplist: [ 'effort_joint_trajectory_controller' ]

  poses_topic: /valve_poses
  angular_speed: 0.5

BACKOFF_VALVE:
  default_outcome: None
  manager_namespace: panda
  startlist: [ 'mpc_controller', 'path_passthrough_controller' ]
  stoplist: [ 'effort_joint_trajectory_controller' ]

  poses_topic: /valve_poses
  offset: [ 0, 0, -0.1 ]
  section: 'last'