# Config file for the combined mission
# Namespaces mirror (optionally) the state for better readability

IDLE:
  default_outcome: None

SETUP:
  default_outcome: None

OPEN_GRIPPER:
  default_outcome: Completed
  gripper_action_name: /franka_gripper/gripper_action
  position: 0.03
  max_effort: 20
  tolerance: 0.001
  timeout: 5.0

CLOSE_GRIPPER:
  default_outcome: Completed
  gripper_action_name: /franka_gripper/gripper_action
  position: 0.0
  max_effort: 20
  tolerance: 0.001
  timeout: 5.0

HOME_ROBOT:
  default_outcome: Completed
  action_name: /joint_space_controller_server
  manager_namespace: control
  startlist: ['joint_space_controller']
  stoplist: ['mpc_controller', 'path_passthrough_controller', 'effort_joint_trajectory_controller']
  joints_configurations:
    - [0, -0.885, 0, -2.1, 0, 1.571, 0]

# hack to avoid self collision in the end
HOME_ROBOT_FINAL:
  default_outcome: Completed
  action_name: /joint_space_controller_server
  manager_namespace: control
  startlist: ['joint_space_controller']
  stoplist: ['mpc_controller', 'path_passthrough_controller', 'effort_joint_trajectory_controller']
  joints_configurations:
    - [-0.65, -0.885, 0, -2.1, 0, 1.571, 0]

FETCH_DETECTION:
  default_outcome: Completed
  detection_topic: "/object_keypoints_ros/pose"

REACH_DETECTION_HOTSPOT:
  default_outcome: Completed
  target_frame: navigation_target
  goal_pose_topic: /move_base_simple/goal
  base_pose_topic: /base_pose_measured
  base_odometry_topic: /base_odom
 
  manager_namespace: control
  startlist: ['smb_diff_drive']
  stoplist: []
  
  timeout: 10000.0
  tolerance_m: 0.30
  tolerance_deg: 50

WAYPOINT_FOLLOWING:
  default_outcome: Completed
  target_frame: navigation_target
  goal_pose_topic: /move_base_simple/goal
  base_pose_topic: /base_pose_measured
  base_odometry_topic: /base_odom
 
  manager_namespace: control
  startlist: ['smb_diff_drive']
  stoplist: []
  
  timeout: 10000.0
  tolerance_m: 0.30
  tolerance_deg: 50

REACH_VIEWPOINT:
  default_outcome: Completed
  action_name: /joint_space_controller_server
  manager_namespace: control
  startlist: ['joint_space_controller']
  stoplist: ['mpc_controller', 'path_passthrough_controller', 'effort_joint_trajectory_controller']
  joints_configurations:
    - [1.57, -0.885, 0, -2.1, 0, 1.571, 0]
    - [-1.57, -0.885, 0, -2.1, 0, 1.571, 0]

LATERAL_GRASP:
  default_outcome: Completed
  controller_name: mpc_controller
  manager_namespace: control
  startlist: ['mpc_controller', 'path_passthrough_controller']
  stoplist: ['joint_space_controller']
  path_topic_name: /desired_path

POST_LATERAL_GRASP:
  default_outcome: Completed
  manager_namespace: control
  startlist: ['mpc_controller', 'path_passthrough_controller']
  stoplist: ['joint_space_controller']
  path_topic_name: /desired_path

MANIPULATE_VALVE:
  default_outcome: Completed
  manager_namespace: control
  startlist: ['mpc_controller', 'path_passthrough_controller']
  stoplist: ['joint_space_controller']
  
  angle_step_deg: -60.0   # how much to rotate at once
  angle_end_deg: -118.0    # total desired rotation
  angle_delta_deg: 5.0    # controls trajectory discretization
  speed_deg: 5.0
  path_topic_name: /desired_path
