# Config file for the combined mission
# Namespaces mirror (optionally) the state for better readability

SETUP:
  default_outcome: None
  #waypoints_file_path: $(find moma_mission)/config/state_machine/piloting_waypoints.yaml

IDLE:
  default_outcome: None

OPEN_GRIPPER:
  default_outcome: None
  gripper_action_name: /panda/franka_gripper/grasp
  position: 0.08
  max_effort: 20
  tolerance: 0.1
  timeout: 35.0

CLOSE_GRIPPER:
  default_outcome: None
  gripper_action_name: /panda/franka_gripper/grasp
  position: 0.0
  max_effort: 1.0
  tolerance: 0.1
  timeout: 10.0

HOME_ROBOT:
  default_outcome: None
  action_name: /joint_space_controller_server
  manager_namespace: panda
  startlist: ["joint_space_controller"]
  stoplist:
    [
      "mpc_controller",
      "mpc_wholebody_controller",
      "cartesian_impedance_controller",
      "path_passthrough_controller",
      "effort_joint_trajectory_controller",
    ]
  joints_configurations:
    - [0, -0.885, 0, -2.1, 0, 1.571, 0.785]

REACH_DETECTION_HOTSPOT_FAR:
  default_outcome: None
  goal_action_topic: /move_base
  target_frame: hotspot_far
  goal_pose_topic: /move_base_simple/goal
  base_pose_topic: /base_pose_measured
  base_odometry_topic: /base_odom

  manager_namespace: smb
  startlist: ["smb_diff_drive"]
  stopmap:
    panda: ["mpc_controller", "mpc_wholebody_controller"]

  timeout: 10000.0
  tolerance_m: 0.30
  tolerance_deg: 50

REACH_DETECTION_HOTSPOT_MEDIUM:
  default_outcome: None
  goal_action_topic: /move_base
  target_frame: hotspot_medium
  goal_pose_topic: /move_base_simple/goal
  base_pose_topic: /base_pose_measured
  base_odometry_topic: /base_odom

  manager_namespace: smb
  startlist: ["smb_diff_drive"]
  stopmap:
    panda: ["mpc_controller", "mpc_wholebody_controller"]

  timeout: 10000.0
  tolerance_m: 0.50
  tolerance_deg: 90

REACH_DETECTION_HOTSPOT_CLOSE:
  default_outcome: None
  duration: 10.0
  control_frame: tracking_camera_odom
  target_frame: hotspot_close
  startlist: ["mpc_wholebody_controller", "path_passthrough_controller"]
  startmap:
    smb: ["smb_diff_drive"]
  stoplist: ["mpc_controller", "joint_space_controller"]
  manager_namespace: panda

WAYPOINT_BROADCAST:
  default_outcome: None
  action_visual_waypoint_frame: valve_gt

WAYPOINT_FOLLOWING:
  default_outcome: None
  goal_action_topic: /move_base
  target_frame: waypoint
  goal_pose_topic: /move_base_simple/goal
  base_pose_topic: /base_pose_measured
  base_odometry_topic: /base_odom

  manager_namespace: smb
  startlist: ["smb_diff_drive"]
  stopmap:
    panda: ["mpc_controller", "mpc_wholebody_controller"]

  timeout: 10000.0
  tolerance_m: 0.30
  tolerance_deg: 50

WAYPOINT_REACHED:
  default_outcome: None

NEW_VALVE:
  post: False

VALVE_ANGLE_CONTROLLER:
  turning_angle_deg: 360.0

DETECTION_DECISION:
  default_outcome: Completed

OBSERVATION_POSE:
  default_outcome: None
  sample_name: observation
  map_frame: tracking_camera_odom
  object_frame: valve_gt
  camera_frame: hand_eye_color_optical_frame
  controlled_frame: tool_frame
  object_size: 0.20
  camera_info_topic: "/camera_info"
  num_samples: 32
  theta_range_deg: [-15, 75]
  phi_range_deg: [30, 40]
  image_fill_ratio_range: [0.4, 0.6]
  heading: "range"
  heading_range_deg: [30, 150] # Don't make this too large (e.g. [0, 180]) since the head orientation could get flipped when going from one extreme to the other

OBSERVATION_APPROACH:
  default_outcome: None
  duration: 1.0
  timeout: 10.0
  control_frame: tracking_camera_odom
  target_frame: observation
  startlist: ["mpc_controller", "path_passthrough_controller"] #, 'path_admittance_controller' ]
  stoplist:
    [
      "mpc_wholebody_controller",
      "cartesian_impedance_controller",
      "joint_space_controller",
    ]
  manager_namespace: panda

MODEL_FIT_VALVE:
  default_outcome: None
  num_spokes: 5
  spoke_radius: 0.01
  handle_radius: 0.015
  dummy: false
  dummy_position: [0.8, 0.0, 0.5]
  dummy_orientation: [0.0, 0.707, 0.0, 0.707]
  error_threshold: 0.01
  min_successful_detections: 3
  feature_matcher_acceptance_ratio: 1000.0
  ransac_min_consensus: 1 #2   # must be > min_successful detections

PLAN_MODEL_VALVE:
  default_outcome: None

  poses_topic: /valve_poses
  approach_poses_topic: /valve_approach_poses
  robot_base_frame: panda_link0
  turning_angle_step_deg: 180.0 # Note that a higher step size than this can result in more entangled trajectories
  safety_distance_factor: 3.8

PLAN_URDF_VALVE:
  default_outcome: None

  poses_topic: /valve_poses
  approach_poses_topic: /valve_approach_poses
  turning_angle_deg: 120.0

APPROACH_HOMING:
  default_outcome: None
  action_name: /joint_space_controller_server
  manager_namespace: panda
  startlist: ["joint_space_controller"]
  stoplist:
    [
      "mpc_controller",
      "mpc_wholebody_controller",
      "path_passthrough_controller",
    ]
  joints_configurations:
    - [1.571, -0.885, 0, -2.1, 0, 1.571, 0.785]

APPROACH_VALVE:
  default_outcome: None
  output: pose
  control_frame: panda_link0
  pose_topic: "/panda/cartesian_impedance_controller/equilibrium_pose"
  manager_namespace: panda
  startlist: ["cartesian_impedance_controller"]
  stoplist:
    [
      "mpc_controller",
      "mpc_wholebody_controller",
      "joint_space_controller",
      "path_passthrough_controller",
    ]
  linear_tolerance: 0.02
  angular_tolerance: 0.1

  poses_topic: /valve_approach_poses
  offset: [0, 0, -0.15]
  timeout: 300.0

GRASP_VALVE:
  default_outcome: None
  output: pose
  control_frame: panda_link0
  pose_topic: "/panda/cartesian_impedance_controller/equilibrium_pose"
  manager_namespace: panda
  startlist: ["cartesian_impedance_controller"]
  stoplist:
    [
      "mpc_controller",
      "mpc_wholebody_controller",
      "joint_space_controller",
      "path_passthrough_controller",
    ]
  linear_tolerance: 0.03 # Make it higher than the one in APPROACH_VALVE, such that this state really only fails if there is a severe problem
  angular_tolerance: 0.15 # Make it higher than the one in APPROACH_VALVE, such that this state really only fails if there is a severe problem

  poses_topic: /valve_poses
  section: "first"
  offset: [0, 0, 0.018]
  timeout: 15.0

MANIPULATE_VALVE:
  default_outcome: None
  output: pose
  linear_speed: 0.1
  angular_speed: 1.0
  control_frame: panda_link0
  pose_topic: "/panda/cartesian_impedance_controller/equilibrium_pose"
  manager_namespace: panda
  startlist: ["cartesian_impedance_controller"]
  stoplist:
    [
      "mpc_controller",
      "mpc_wholebody_controller",
      "joint_space_controller",
      "path_passthrough_controller",
    ]

  poses_topic: /valve_poses

MANIPULATE_VALVE_STEP_COMPLETED:
  post: True

STORE_FINAL_POSE:
  default_outcome: None
  target_frame: tool_frame
  control_frame: tracking_camera_odom
  store_frame: final_pose

APPROACH_FINAL_POSE:
  default_outcome: None
  target_frame: final_pose
  control_frame: panda_link0
  output: pose
  pose_topic: "/panda/cartesian_impedance_controller/equilibrium_pose"
  startlist: ["cartesian_impedance_controller"]
  stoplist: []
  manager_namespace: panda

BACKOFF_VALVE:
  default_outcome: None
  target_frame: final_pose
  control_frame: panda_link0
  output: pose
  pose_topic: "/panda/cartesian_impedance_controller/equilibrium_pose"
  manager_namespace: panda
  startlist: ["cartesian_impedance_controller"]
  stoplist: []

  duration: 30.0
  offset: [0, 0, -0.1]
  linear_tolerance: 0.05
  angular_tolerance: 0.3
