<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="superpanda">

  <!-- MPC Arguments -->
  <xacro:arg name="mpc_model" default="false"/>

  <xacro:if value="$(arg mpc_model)">
    <link name="world" />
    <joint name="base_prismatic_x" type="prismatic">
      <parent link="world" />
      <child link="base_x" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
      <limit effort="0" velocity="0"/>
    </joint>
    <link name="base_x" />
    <joint name="base_prismatic_y" type="prismatic">
      <parent link="base_x" />
      <child link="base_y" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="0" velocity="0"/>
    </joint>
    <link name="base_y" />
    <joint name="base_revolute_theta" type="revolute">
      <parent link="base_y" />
      <child link="base_theta" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="0" velocity="0"/>
    </joint>
    <link name="base_theta" />
    <joint name="base_to_panda" type="fixed">
      <parent link="base_theta" />
      <child link="base_link" />
      <origin xyz="0 0 0.2" rpy="0 0 0"/>
    </joint>
    <link name="base_link" />
  </xacro:if>

  <!-- SMB Arguments -->
  <xacro:arg name="wheel_joint_type"          default="continuous"/>
  <xacro:arg name="simulation"                default="true"/>
  <xacro:arg name="use_ros_skid_steer"        default="false"/>  <!-- This does not work nicely -->
  <xacro:arg name="use_ros_control"           default="false"/>  <!-- Set to faulse as we import already a plugin for the arm-->
  <xacro:arg name="lidar"                     default="true"/>
  <xacro:arg name="robot_namespace"           default=""/>
  <xacro:arg name="description_name_xacro"    default="robot_description"/>
  <xacro:arg name="publish_tf"                default="true"/>
  <xacro:arg name="tracking_camera"           default="true"/>
  <xacro:property name="lidar" value="$(arg lidar)"/>

  <!-- SMB Includes -->
  <xacro:include filename="$(find smb_description)/urdf/smb_piloting_properties.urdf.xacro" />

  <xacro:unless value="$(arg mpc_model)">

    <xacro:if value="$(arg simulation)">
      <xacro:include filename="$(find smb_description)/urdf/smb_gazebo_addins.urdf.xacro"/>
    </xacro:if>

    <!-- SMB -->
    <xacro:include filename="$(find smb_description)/urdf/smb.urdf.xacro">
      <xacro:arg name="lidar" default="$(arg lidar)"/>
    </xacro:include>
    <xacro:smb wheel_joint_type="$(arg wheel_joint_type)" simulation="$(arg simulation)" tracking_camera="$(arg tracking_camera)"/>

  </xacro:unless>

  <!-- Rigid fix between SMB and Panda -->
  <link name="arm_mount_link"/>
  <joint name="arm_mount_joint" type="fixed">
    <parent link="base_link" />
    <child link="arm_mount_link" />
    <origin xyz="0.115 0.0 ${0.228+chassisHeight/2.0}" rpy="0 0 0"/>
  </joint>

  <!-- Panda Arguments -->
  <xacro:arg name="use_fixed_realsense" default="false"/>
  <xacro:arg name="tool" default="panda_hand"/>
  <xacro:arg name="control_mode" default='Position'/>

  <xacro:include filename="$(find moma_description)/urdf/panda.xacro"/>
  <xacro:panda connected_to="arm_mount_link" use_fixed_realsense="$(arg use_fixed_realsense)" control_mode="$(arg control_mode)" tool="$(arg tool)" include_gazebo_control="true" robot_namespace="" control_namespace="control"/>


</robot>
