joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

position_joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  constraints:
    goal_time: 0.5

joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: panda_joint1
  pid: {p: 100.0, i: 0.1, d: 10.0}

joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: panda_joint2
  pid: {p: 100.0, i: 0.1, d: 10.0}

joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: panda_joint3
  pid: {p: 100.0, i: 0.1, d: 10.0}

joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: panda_joint4
  pid: {p: 100.0, i: 0.1, d: 10.0}

joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: panda_joint5
  pid: {p: 100.0, i: 0.1, d: 10.0}

joint6_position_controller:
  type: effort_controllers/JointPositionController
  joint: panda_joint6
  pid: {p: 100.0, i: 0.1, d: 10.0}

joint7_position_controller:
  type: effort_controllers/JointPositionController
  joint: panda_joint7
  pid: {p: 50.0, i: 0.1, d: 10.0}

franka_gripper:
  type: position_controllers/GripperActionController
  joint: panda_finger_joint1

gazebo_ros_control:
  pid_gains:
    panda_finger_joint1: {p: 100, i: 0.1, d: 10, i_clamp: 0.2}
    panda_finger_joint2: {p: 100, i: 0.1, d: 10, i_clamp: 0.2}
    front_left_wheel: {p: 1, i: 0.1, d: 0, i_clamp: 0.2}
    front_right_wheel: {p: 1, i: 0.1, d: 0, i_clamp: 0.2}
    rear_left_wheel: {p: 1, i: 0.1, d: 0, i_clamp: 0.2}
    rear_right_wheel: {p: 1, i: 0.1, d: 0, i_clamp: 0.2}

