# Define the goal
uint32 num_scan_poses  # Specify which dishwasher we want to use
---
# Define the result
bool success
---
# Define a feedback message
float32 percent_complete
bool pointcloud_read_success
