image_width: 1280
image_height: 720
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [923.003325, 0., 626.0, 0., 923.00325, 364.0, 0., 0., 1.]
distortion_model: radtan
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.0, 0.0, 0.0, 0.0, 0.0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0., 0., 1., 0., 0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [923.003325, 0., 626.0, 0., 0., 923.003325, 364.0, 0., 0., 0., 1., 0.]
