gazebo_ros_control:
  pid_gains:
    front_left_wheel: {p: 1, i: 0.1, d: 0}
    front_right_wheel: {p: 1, i: 0.1, d: 0}
    rear_left_wheel: {p: 1, i: 0.1, d: 0}
    rear_right_wheel: {p: 1, i: 0.1, d: 0}
    front_rocker: {p: 0, i: 0, d: 0}
