Forward:
  joint_positions:
    panda_joint1: 0.0
    panda_joint2: 0.0
    panda_joint3: 0.0
    panda_joint4: -1.57
    panda_joint5: 0.0
    panda_joint6: 1.54
    panda_joint7: 0.0
Home:
  joint_positions:
    panda_joint1: 0.0
    panda_joint2: 0.0
    panda_joint3: 0.0
    panda_joint4: 0.0
    panda_joint5: 0.0
    panda_joint6: 0.0
    panda_joint7: 0.0
Up:
  joint_positions:
    panda_joint1: 0.0
    panda_joint2: 0.0
    panda_joint3: 0.0
    panda_joint4: 0.0
    panda_joint5: 0.0
    panda_joint6: 3.14
    panda_joint7: 0.0
