controller_list:
  - name: fake_wbc_controller
    joints:
      - world_base_x
      - world_base_y
      - world_base_th
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
  - name: fake_hand_controller
    joints:
      - panda_finger_joint1