<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="container_no_lid">

<xacro:include filename="container_common.xacro"/>

<link name="base_link">
  <inertial>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <mass value="0.0"/>
    <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
  </inertial>
</link>

<xacro:corpus prefix="frame" width="${total_width}" depth="${total_depth}" height="${total_height-wall_thickness}" wall_thickness="${wall_thickness}" color="dark_brown"/>
<joint name="frame_joint" type="fixed">
  <origin xyz="0 0 ${wall_thickness/2}" rpy="0 0 0"/>
  <parent link="base_link"/>
  <child link="frame_bottom_plane"/>
</joint>

<xacro:plane prefix="lid" width="${total_width*1.05}" depth="${total_depth*1.05}" thickness="${wall_thickness}" color="white"/>
<joint name="lid_joint" type="prismatic">
  <origin xyz="0 0 ${total_height-wall_thickness}" rpy="0 0 0"/>
  <parent link="frame_bottom_plane"/>
  <child link="lid_plane"/>
  <axis xyz="1 0 0"/>
  <dynamics damping="8.0"/>
  <limit lower="0.0" upper="${0.9*total_width}" effort="10.0" velocity="1.5"/>
</joint>

<xacro:handle length="${total_depth*0.8}"/>
<joint name="handle_joint" type="fixed">
  <origin xyz="0 0 ${wall_thickness/2+0.02}" rpy="${pi/2} 0 0"/>
  <parent link="lid_plane"/>
  <child link="handle"/>
</joint>

</robot>
