# Publish transforms for any moving joints
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

# Joint trajectory controller
franka/position_joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
    - world_base_x
    - world_base_y
    - world_base_th
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.1
    panda_joint1:
      goal: 0.05
    panda_joint2:
      goal: 0.05
    panda_joint3:
      goal: 0.05
    panda_joint4:
      goal: 0.05
    panda_joint5:
      goal: 0.05
    panda_joint6:
      goal: 0.05
    panda_joint7:
      goal: 0.05
    world_base_x:
      goal: 0.05
    world_base_y:
      goal: 0.05
    world_base_th:
      goal: 0.05

franka/gripper_action_controller:
  type: "position_controllers/GripperActionController"
  joint: panda_finger_joint1
