gazebo_ros_control:
  pid_gains:
    panda_joint1: {p: 50, i: 0, d: 20}
    panda_joint2: {p: 10000, i: 0, d: 500}
    panda_joint3: {p: 100, i: 0, d: 10}
    panda_joint4: {p: 1000, i: 0, d: 50}
    panda_joint5: {p: 100, i: 0, d: 10}
    panda_joint6: {p: 100, i: 0, d: 10}
    panda_joint7: {p: 10, i: 0.5, d: 0.1}
    panda_finger_joint1: {p: 100, i: 0, d: 50}
    panda_finger_joint2: {p: 100, i: 0, d: 50}
    front_left_wheel: {p: 1, i: 0.1, d: 0}
    front_right_wheel: {p: 1, i: 0.1, d: 0}
    rear_left_wheel: {p: 1, i: 0.1, d: 0}
    rear_right_wheel: {p: 1, i: 0.1, d: 0}
    front_rocker: {p: 0, i: 0, d: 0}
    world_base_x: {p: 10000, i: 0, d: 1000}
    world_base_y: {p: 10000, i: 0, d: 1000}
    world_base_th: {p: 1000, i: 0, d: 0}
