gazebo_ros_control:
  pid_gains:
    panda_finger_joint1: {p: 100, i: 0, d: 50}
    panda_finger_joint2: {p: 100, i: 0, d: 50}

    panda_joint1: {p: 150, i: 0, d: 20}
    panda_joint2: {p: 30000, i: 0, d: 500}
    panda_joint3: {p: 300, i: 0, d: 10}
    panda_joint4: {p: 3000, i: 0, d: 50}
    panda_joint5: {p: 300, i: 0, d: 10}
    panda_joint6: {p: 300, i: 0, d: 10}
    panda_joint7: {p: 30, i: 0.5, d: 0.1}
