---
- hosts: franka-box
  remote_user: franka
  tasks:
    - name: Update package lists
      become: yes
      apt:
        update_cache: true
    - name: Install ros-franka
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - ros-melodic-franka-ros
    - name: Create workspace src directory
      file:
        path: /home/franka/catkin_ws/src/
        state: directory
    - name: Initialize workspace
      shell: catkin init
      args:
        chdir: /home/franka/catkin_ws
    - name: Should clone repository
      debug:
        msg: Currently I (@kekeblom) don't have access to the repository settings so I can't setup a deploy key. Repository has to be cloned manually for now.


