---
- hosts: franka-box
  remote_user: franka
  tasks:
    - name: Add key to keyserver
      become: yes
      apt_key:
        keyserver: keys.gnupg.net
        id: F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE
        state: present
    - name: Add apt repository
      become: yes
      apt_repository:
        repo: deb http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic main
        state: present
    - name: Update package lists
      become: yes
      apt:
        update_cache: true
    - name: Install apt packages
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - librealsense2-dkms
        - librealsense2-utils
        - librealsense2-dev
        - librealsense2-dbg
        - ros-melodic-ddynamic-reconfigure
    - name: Clone intelrealsense repo
      git:
        repo: https://github.com/IntelRealSense/realsense-ros.git
        dest: /home/franka/catkin_ws/src/realsense-ros.git
