---
- hosts: franka-box
  remote_user: franka
  tasks:
    - name: Add apt repository
      become: yes
      apt_repository:
        repo: deb http://packages.ros.org/ros/ubuntu xenial main
        state: present
    - name: Add key to keyserver
      become: yes
      apt_key:
        keyserver: hkp://ha.pool.sks-keyservers.net:80
        id: 421C365BD9FF1F717815A3895523BAEEB01FA116
        state: present
    - name: Update package lists
      become: yes
      apt:
        update_cache: true
    - name: Install ros.
      become: yes
      apt:
        name: ros-melodic-ros-base
        state: present
    - name: Rosdep update
      shell: |
        rosdep init
        rosdep update
    - name: Source ros in bashrc
      lineinfile: dest=~/.bashrc regexp="^source \/opt\/ros\/melodic\/setup.bash" line="source /opt/ros/melodic/setup.bash"
    - name: Install python-rosinstall
      become: yes
      apt:
        name: python-rosinstall
        state: present
    - name: Install python-rosinstall-generator
      become: yes
      apt:
        name: python-rosinstall-generator
        state: present
    - name: Install python-wstool
      become: yes
      apt:
        name: python-wstool
        state: present
    - name: Install build-essential
      become: yes
      apt:
        name: build-essential
        state: present

