name: CI

on:
  pull_request:
    branches: [projects/piloting_feature/ci]
  push:

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Linting
        run: |
          pip install pre-commit
          pre-commit run --all-files

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install ROS Noetic
        id: ros_setup
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: noetic

      - name: Setup ROS workspace
        uses: ros-tooling/action-ros-ci@v0.2
        id: ros_workspace
        with:
          target-ros1-distro: noetic

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          path: ${{steps.ros_workspace.outputs.ros-workspace-directory-name}}

      - run: |
          export CATKIN_WS=${{steps.ros_setup.outputs.ros-workspace-directory-name}}
          echo "::set-env name=CATKIN_WS::$CATKIN_WS"
      - run: sudo apt install python3-vcstool
      - run: |
          echo "cd $CATKIN_WS/src"
          cd $CATKIN_WS/src
      - run: vcs import --recursive --input moma/moma_core.repos
      - run: vcs import --recursive --input moma/moma_piloting.repos
      - run: ./moma/install_dependencies.sh --control
      - run: source ../devel/setup.bash
      - run: catkin build --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo
