name: CI

on:
  pull_request:
    branches: [projects/piloting_feature/ci]
  push:

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Linting
        run: |
          pip install pre-commit
          pre-commit run --all-files

  build:
    runs-on: ubuntu-latest
    container:
      image: ros:noetic

    steps:
      - name: Init workspace
        run: |
          mkdir -p catkin_ws/src && cd catkin_ws/src
          echo "::set-env name=pwd

      - run: mkdir -p catkin_ws/src

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          path: ~/catkin_ws/src

      - name: Install Dependencies
        run: |
          cd ~/catkin_ws/src
          vcs import --recursive --input moma/moma_core.repos
          vcs import --recursive --input moma/moma_piloting.repos
           ./moma/install_dependencies.sh --control

      - name: Build
        run: |
          source ../devel/setup.bash
          catkin build --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo
