icp_localization:
  initial_pose:
    x: 1.283 
    y: -0.876 
    z: 0.326 
    roll: 0.0  #rpy in deg
    pitch: 0.0
    yaw: 88.0 
  imu_data_topic: "/versavis/imu" #"/sensors/imu" #
  odometry_data_topic: "/camera/odom/sample" #"/camera/odom/sample" "/msf_core/odometry" #
  num_accumulated_range_data: 1
  range_data_topic: "/rslidar_points" # "/point_cloud_filter/velodyne/point_cloud_filtered" #
  is_use_odometry: true
  is_provide_odom_frame: true
  gravity_vector_filter_time_constant: 0.01
  fixed_frame: "map"
  min_num_odom_msgs_before_ready: 300


calibration:
  imu_to_range_sensor:
    x: -0.01
    y: 0.024
    z: 0.326
    roll: 0.0
    pitch: 0.0
    yaw: 1.571  
  odometry_source_to_range_sensor:
    x: -0.064
    y: -0.008
    z: 0.154
    roll: 0.0
    pitch: 0.0
    yaw: 1.571  
