panda:
  panda_joint1:
    type: effort_controllers/JointVelocityController
    joint: panda_joint1
    pid:
      p: 120
      i: 10
      d: 1

  panda_joint2:
    type: effort_controllers/JointVelocityController
    joint: panda_joint2
    pid:
      p: 500
      i: 100
      # i_clamp: 1000

  panda_joint3:
    type: effort_controllers/JointVelocityController
    joint: panda_joint3
    pid:
      p: 180
      i: 1
      # i_clamp: 0.1

  panda_joint4:
    type: effort_controllers/JointVelocityController
    joint: panda_joint4
    pid:
      p: 10000
      i: 2000
      # i_clamp: 0.0

  panda_joint5:
    type: effort_controllers/JointVelocityController
    joint: panda_joint5
    pid:
      p: 180
      i: 1
      # i_clamp: 0.1

  panda_joint6:
    type: effort_controllers/JointVelocityController
    joint: panda_joint6
    pid:
      p: 180
      i: 1
      # i_clamp: 0.1

  panda_joint7:
    type: effort_controllers/JointVelocityController
    joint: panda_joint7
    pid:
      p: 180
      i: 1
      # i_clamp: 0.1
